### ISSUE TITLE
Grid image

### ISSUE THREAD

**Issue by AviFix** [agreatfool/image-merge-dir#1]
Hi,

Thanks for the feat project.

I seem to have some spaces between the images.
How could i get rid of them?

Thanks a lot
Avi

**Comment by agreatfool** [comment]
Sorry for the late reply.

Please see the command line output command info, like: 

```javascript
console.log(`Merge images with command: ${command}`);
```
It shall be:
https://github.com/agreatfool/image-merge-dir/blob/cdf62b7f877faa34f659db4a0a68a1634ca021bc/src/index.ts#L199

If you don't want spaces between images, remove the `-geometry +2+2`, and have a try, execute with yourself.

Best Regards

**Comment by AviFix** [comment]
Hi @agreatfool,

That did it.

Thanks a lot
Avi
